version: '3'

services:
  PostgreSQL:
    image: postgres:10-alpine                                                                                                                                    
    container_name: PostgreSQL
    restart: always
    environment: 
      POSTGRES_PASSWORD: kugsig17
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:                                                                                                                                                 
      - ./postgres:/var/lib/postgresql/data
    networks:                                                                                                                                                
      - ahiqar 

networks:
  ahiqar: